config_version: none
mysql_enabled: false
min_amount: 300
max_amount: 1000000
time_expire: 60
tax_percentage: 5
formatting_shorten_money: true
sound_while_choosing: BLOCK_DISPENSER_DISPENSE
sound_winner_chosen: ENTITY_FIREWORK_BLAST
frame_winner_chosen: 30
boosters_enabled: false
animation_default: default
bets_per_player: 1
gui_auto_close: true
value_needed_to_broadcast: 100000
sign_input: true
disabled_worlds: disabledWorld1,disabledWorld2