config_version: none
min_amount: 300
max_amount: 1000000
time_expire: 60
tax_percentage: 5
sound_while_choosing: BLOCK_DISPENSER_DISPENSE
sound_winner_chosen: ENTITY_FIREWORK_BLAST
boosters_enabled: false
animation_default: default
bets_per_player: 1