name: CoinFlipper
version: 1.92
author: gronnmann
main: io.github.gronnmann.coinflipper.Main
depend: [Vault]
softdepend: [ProtocolLib, CombatTagPlus, PvPManager]
commands:
    coinflipper:
        aliases: [ cf, coinflip ]