name: CoinFlipper
version: 1.84
author: gronnmann
main: io.github.gronnmann.coinflipper.Main
depend: [Vault]
softdepend: [CombatTagPlus, PvPManager, ProtocolLib]
commands:
    coinflipper:
        aliases: [ cf, coinflip ]