name: CoinFlipper
version: 1.73
author: gronnmann
main: io.github.gronnmann.coinflipper.Main
depend: [Vault]
softdepend: [CombatTagPlus, PvPManager]
commands:
    coinflipper:
        aliases: [ cf, coinflip ]