name: CoinFlipper
version: 2.4
author: gronnmann
main: io.github.gronnmann.coinflipper.Main
depend: [Vault]
softdepend: [ProtocolLib, CombatTagPlus, PvPManager, ChatPerWorld, CombatLogX, PlaceholderAPI]
commands:
    coinflipper:
        aliases: [ cf, coinflip ]