name: SkittleMCCoinFlip
version: 2.93
author: VirusDetected, gronnmann
main: io.github.gronnmann.coinflipper.CoinFlipper
depend: [Vault]
softdepend: [ProtocolLib, CombatTagPlus, PvPManager, ChatPerWorld, CombatLogX, PlaceholderAPI]
commands:
    coinflipper:
        aliases: [ cf, coinflip ]